# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-13 00:45:37
"""
import arcpy
def #  NOT  IMPLEMENTED# Function Body not implemented

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"d:\download\arcgis pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    arcpy.ImportToolbox(r"d:\download\arcgis pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder1_Project\\Floder8_Project.gdb", workspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Project\\Project.gdb"):
        Floder8_Project_gdb = "D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb"

        for Raster, Name in #  NOT  IMPLEMENTED(Floder8_Project_gdb, "", "", "NOT_RECURSIVE"):

            # Process: Raster to Polygon (栅格转面) (conversion)
            Output_polygon_features = "D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb\\RasterT_changed1"
            with arcpy.EnvManager(configKeyword=Name, outputMFlag="Disabled", outputZFlag="Disabled"):
                arcpy.conversion.RasterToPolygon(in_raster=Raster, out_polygon_features=Output_polygon_features)

            # Process: Add Geometry Attributes (添加几何属性) (management)
            RasterT_changed1 = arcpy.management.AddGeometryAttributes(Input_Features=Output_polygon_features, Geometry_Properties=["AREA", "PERIMETER_LENGTH"], Length_Unit="METERS", Area_Unit="SQUARE_METERS", Coordinate_System="PROJCS[\"WGS_1984_World_Mercator\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],UNIT[\"Meter\",1.0]]")[0]

            # Process: Select (选择) (analysis)
            Output_Feature_Class = "D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb\\RasterT_changed1_Select"
            with arcpy.EnvManager(scratchWorkspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb", workspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb"):
                arcpy.analysis.Select(in_features=RasterT_changed1, out_feature_class=Output_Feature_Class)

            # Process: Dissolve (融合) (management)
            Name_Dissolve = "D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb\\RasterT_changed1_Select_Diss"
            with arcpy.EnvManager(scratchWorkspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb", workspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb"):
                arcpy.management.Dissolve(in_features=Output_Feature_Class, out_feature_class=Name_Dissolve, dissolve_field=["gridcode"], statistics_fields=[["POLY_AREA", "SUM"], ["PERIMETER", "SUM"], ["gridcode", "COUNT"]])

            # Process: Define Projection (定义投影) (management)
            with arcpy.EnvManager(scratchWorkspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb", workspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb"):
                Name_Dissolve_2_ = arcpy.management.DefineProjection(in_dataset=Name_Dissolve, coor_system="PROJCS[\"WGS_1984_World_Mercator\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],UNIT[\"Meter\",1.0]]")[0]

            # Process: Add Fields (multiple) (添加字段(多个)) (management)
            with arcpy.EnvManager(scratchWorkspace="D:\\Esri\\Project\\Project1\\Floder8_Project\\Floder8_Project.gdb", workspace="D:\\Esri\\Project\\Project1\\Floder8_Project\\Floder8_Project.gdb"):
                Name_Dissolve_3_ = arcpy.management.AddFields(in_table=Name_Dissolve_2_)[0]

            # Process: Calculate Geometry Attributes (计算几何属性) (management)
            with arcpy.EnvManager(scratchWorkspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb", workspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb"):
                Name_Dissolve_4_ = arcpy.management.CalculateGeometryAttributes(in_features=Name_Dissolve_3_, geometry_property=[["x", "CENTROID_X"], ["y", "CENTROID_Y"]], coordinate_system="PROJCS[\"WGS_1984_World_Mercator\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],UNIT[\"Meter\",1.0]]")[0]

            # Process: Table To Excel (表转 Excel) (conversion)
            Name = "changed_WH_JB_huanghelou_003_12_classified"
            _Name_xls = fr"D:\通用文件夹\空间分析项目\Project1\Result_Table_5k\{Name}.xls"
            with arcpy.EnvManager(scratchWorkspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb", workspace="D:\\通用文件夹\\空间分析项目\\Project1\\Project1\\Floder_Project\\Floder_Project.gdb"):
                arcpy.conversion.TableToExcel(Input_Table=Name_Dissolve_4_, Output_Excel_File=_Name_xls)

if __name__ == '__main__':
    Model()
