# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-13 01:30:11
"""
import arcpy
from arcpy.sa import *

def Model2():  # 模型2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    shenzhen_svi_result_XYTableToPoint = "shenzhen_svi_result_XYTableToPoint"
    reclas_raste_tif = arcpy.Raster("reclas_raste.tif")

    # Process: 缓冲区 (缓冲区) (analysis)
    shenzhen_svi_result_X_Buffer = "E:\\MyProject\\MyProject.gdb\\shenzhen_svi_result_X_Buffer"
    arcpy.analysis.Buffer(in_features=shenzhen_svi_result_XYTableToPoint, out_feature_class=shenzhen_svi_result_X_Buffer, buffer_distance_or_field="200 Meters")

    # Process: 以表格显示分区统计 (以表格显示分区统计) (sa)
    ZonalSt_shenzhe1 = "E:\\MyProject\\MyProject.gdb\\ZonalSt_shenzhe1"
    arcpy.sa.ZonalStatisticsAsTable(shenzhen_svi_result_X_Buffer, "id", reclas_raste_tif, ZonalSt_shenzhe1, "DATA", "MEAN", "CURRENT_SLICE", 90, "AUTO_DETECT", "ARITHMETIC", 360)
    .save(以表格显示分区统计)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="E:\\MyProject\\MyProject.gdb", workspace="E:\\MyProject\\MyProject.gdb"):
        Model2()
