# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-13 00:54:43
"""
import arcpy
from arcpy.sa import *

def Model1():  # 模型1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    lvbo4 = arcpy.Raster("lvbo4")

    # Process: 山体阴影 (山体阴影) (3d)
    HillSha_lvbo1 = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1, azimuth=70.82, altitude=16.16, model_shadows="SHADOWS")
    HillSha_lvbo1 = arcpy.Raster(HillSha_lvbo1)

    # Process: 重分类 (重分类) (3d)
    Reclass_Hill1 = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1)
    Reclass_Hill1 = arcpy.Raster(Reclass_Hill1)

    # Process: 山体阴影 (2) (山体阴影) (3d)
    HillSha_lvbo1_2_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_2_, azimuth=74.88, altitude=29.37, model_shadows="SHADOWS")
    HillSha_lvbo1_2_ = arcpy.Raster(HillSha_lvbo1_2_)

    # Process: 重分类 (2) (重分类) (3d)
    Reclass_Hill1_2_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_2_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_2_)
    Reclass_Hill1_2_ = arcpy.Raster(Reclass_Hill1_2_)

    # Process: 山体阴影 (3) (山体阴影) (3d)
    HillSha_lvbo1_3_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_3_, azimuth=78.31, altitude=42.84, model_shadows="SHADOWS")
    HillSha_lvbo1_3_ = arcpy.Raster(HillSha_lvbo1_3_)

    # Process: 重分类 (3) (重分类) (3d)
    Reclass_Hill1_3_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_3_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_3_)
    Reclass_Hill1_3_ = arcpy.Raster(Reclass_Hill1_3_)

    # Process: 山体阴影 (4) (山体阴影) (3d)
    HillSha_lvbo1_4_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_4_, azimuth=81.21, altitude=56.69, model_shadows="SHADOWS")
    HillSha_lvbo1_4_ = arcpy.Raster(HillSha_lvbo1_4_)

    # Process: 重分类 (4) (重分类) (3d)
    Reclass_Hill1_4_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_4_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_4_)
    Reclass_Hill1_4_ = arcpy.Raster(Reclass_Hill1_4_)

    # Process: 山体阴影 (5) (山体阴影) (3d)
    HillSha_lvbo1_5_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_5_, azimuth=83.17, altitude=70.18, model_shadows="SHADOWS")
    HillSha_lvbo1_5_ = arcpy.Raster(HillSha_lvbo1_5_)

    # Process: 重分类 (5) (重分类) (3d)
    Reclass_Hill1_5_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_5_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_5_)
    Reclass_Hill1_5_ = arcpy.Raster(Reclass_Hill1_5_)

    # Process: 山体阴影 (6) (山体阴影) (3d)
    HillSha_lvbo1_6_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_6_, azimuth=80.44, altitude=83.69, model_shadows="SHADOWS")
    HillSha_lvbo1_6_ = arcpy.Raster(HillSha_lvbo1_6_)

    # Process: 重分类 (6) (重分类) (3d)
    Reclass_Hill1_6_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_6_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_6_)
    Reclass_Hill1_6_ = arcpy.Raster(Reclass_Hill1_6_)

    # Process: 山体阴影 (7) (山体阴影) (3d)
    HillSha_lvbo1_7_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_7_, azimuth=278.27, altitude=82.16, model_shadows="SHADOWS")
    HillSha_lvbo1_7_ = arcpy.Raster(HillSha_lvbo1_7_)

    # Process: 重分类 (7) (重分类) (3d)
    Reclass_Hill1_7_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_7_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_7_)
    Reclass_Hill1_7_ = arcpy.Raster(Reclass_Hill1_7_)

    # Process: 山体阴影 (8) (山体阴影) (3d)
    HillSha_lvbo1_8_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_8_, azimuth=277, altitude=68.41, model_shadows="SHADOWS")
    HillSha_lvbo1_8_ = arcpy.Raster(HillSha_lvbo1_8_)

    # Process: 重分类 (8) (重分类) (3d)
    Reclass_Hill1_8_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_8_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_8_)
    Reclass_Hill1_8_ = arcpy.Raster(Reclass_Hill1_8_)

    # Process: 山体阴影 (9) (山体阴影) (3d)
    HillSha_lvbo1_9_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_9_, azimuth=279.17, altitude=54.7, model_shadows="SHADOWS")
    HillSha_lvbo1_9_ = arcpy.Raster(HillSha_lvbo1_9_)

    # Process: 重分类 (9) (重分类) (3d)
    Reclass_Hill1_9_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_9_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_9_)
    Reclass_Hill1_9_ = arcpy.Raster(Reclass_Hill1_9_)

    # Process: 山体阴影 (10) (山体阴影) (3d)
    HillSha_lvbo1_10_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_10_, azimuth=282.1, altitude=41.09, model_shadows="SHADOWS")
    HillSha_lvbo1_10_ = arcpy.Raster(HillSha_lvbo1_10_)

    # Process: 重分类 (10) (重分类) (3d)
    Reclass_Hill1_10_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_10_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_10_)
    Reclass_Hill1_10_ = arcpy.Raster(Reclass_Hill1_10_)

    # Process: 山体阴影 (11) (山体阴影) (3d)
    HillSha_lvbo1_11_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_11_, azimuth=285.6, altitude=27.65, model_shadows="SHADOWS")
    HillSha_lvbo1_11_ = arcpy.Raster(HillSha_lvbo1_11_)

    # Process: 重分类 (11) (重分类) (3d)
    Reclass_Hill1_11_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_11_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_11_)
    Reclass_Hill1_11_ = arcpy.Raster(Reclass_Hill1_11_)

    # Process: 山体阴影 (12) (山体阴影) (3d)
    HillSha_lvbo1_12_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_12_, azimuth=289.68, altitude=14.7, model_shadows="SHADOWS")
    HillSha_lvbo1_12_ = arcpy.Raster(HillSha_lvbo1_12_)

    # Process: 重分类 (12) (重分类) (3d)
    Reclass_Hill1_12_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_12_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_12_)
    Reclass_Hill1_12_ = arcpy.Raster(Reclass_Hill1_12_)

    # Process: 山体阴影 (13) (山体阴影) (3d)
    HillSha_lvbo1_13_ = "E:\\MyProject\\MyProject.gdb\\HillSha_lvbo1"
    arcpy.ddd.HillShade(in_raster=lvbo4, out_raster=HillSha_lvbo1_13_, azimuth=294.79, altitude=1.91, model_shadows="SHADOWS")
    HillSha_lvbo1_13_ = arcpy.Raster(HillSha_lvbo1_13_)

    # Process: 重分类 (13) (重分类) (3d)
    Reclass_Hill1_13_ = "E:\\MyProject\\MyProject.gdb\\Reclass_Hill1"
    arcpy.ddd.Reclassify(in_raster=HillSha_lvbo1_13_, reclass_field="VALUE", remap="0 1 0;1 254 1", out_raster=Reclass_Hill1_13_)
    Reclass_Hill1_13_ = arcpy.Raster(Reclass_Hill1_13_)

    # Process: 栅格计算器 (栅格计算器) (sa)
    reclas_raste = "e:\\myproject\\myproject.gdb\\reclas_raste"
    栅格计算器 = reclas_raste
    reclas_raste =  Reclass_Hill1 + Reclass_Hill1_2_ + Reclass_Hill1_3_ + Reclass_Hill1_4_ + Reclass_Hill1_5_ + Reclass_Hill1_6_ + Reclass_Hill1_7_ + Reclass_Hill1_8_ + Reclass_Hill1_9_ + Reclass_Hill1_10_ + Reclass_Hill1_11_ + Reclass_Hill1_12_ + Reclass_Hill1_13_
    reclas_raste.save(栅格计算器)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="E:\\MyProject\\MyProject.gdb", workspace="E:\\MyProject\\MyProject.gdb"):
        Model1()
