# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-12 18:57:54
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # 模型

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    建筑矢量数据 = "建筑矢量数据"
    dem数字高程模型 = arcpy.Raster("dem数字高程模型")

    # Process: 面转栅格 (面转栅格) (conversion)
    建筑栅格数据 = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\建筑栅格数据"
    arcpy.conversion.PolygonToRaster(in_features=建筑矢量数据, value_field="建筑高度", out_rasterdataset=建筑栅格数据)

    # Process: 重采样 (重采样) (management)
    建筑栅格数据_2_ = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\建筑栅格数据"
    arcpy.management.Resample(in_raster=建筑栅格数据, out_raster=建筑栅格数据_2_)
    建筑栅格数据_2_ = arcpy.Raster(建筑栅格数据_2_)

    # Process: 按掩膜提取 (按掩膜提取) (sa)
    掩膜后dem = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\掩膜后dem"
    按掩膜提取 = 掩膜后dem
    掩膜后dem = arcpy.sa.ExtractByMask(dem数字高程模型, 建筑矢量数据, "INSIDE", "DEFAULT")
    掩膜后dem.save(按掩膜提取)


    # Process: 分区统计 (分区统计) (sa)
    建筑区域平均后的dem = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\建筑区域平均后的dem"
    分区统计 = 建筑区域平均后的dem
    建筑区域平均后的dem = arcpy.sa.ZonalStatistics(建筑栅格数据, "建筑id", 掩膜后dem, "MEAN", "DATA", "CURRENT_SLICE", 90, "AUTO_DETECT", "ARITHMETIC", 360)
    建筑区域平均后的dem.save(分区统计)


    # Process: 滤波器 (滤波器) (sa)
    平滑的dem = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\平滑的dem"
    滤波器 = 平滑的dem
    平滑的dem = arcpy.sa.Filter(建筑区域平均后的dem, "LOW", "DATA")
    平滑的dem.save(滤波器)


    # Process: 重采样 (2) (重采样) (management)
    模拟dem数字高程模型 = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\模拟dem数字高程模型"
    arcpy.management.Resample(in_raster=平滑的dem, out_raster=模拟dem数字高程模型)
    模拟dem数字高程模型 = arcpy.Raster(模拟dem数字高程模型)

    # Process: 加 (加) (3d)
    最终的模拟dsm数字表面模型 = "C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb\\最终的模拟dsm数字表面模型"
    arcpy.ddd.Plus(in_raster_or_constant1=建筑栅格数据_2_, in_raster_or_constant2=模拟dem数字高程模型, out_raster=最终的模拟dsm数字表面模型)
    最终的模拟dsm数字表面模型 = arcpy.Raster(最终的模拟dsm数字表面模型)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb", workspace="C:\\Users\\Administrator\\Documents\\ArcGIS\\Projects\\MyProject8\\MyProject8.gdb"):
        Model()
